const $=s=>document.querySelector(s),page=$('#page');
const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const sess={get token(){return sessionStorage.token},get role(){return sessionStorage.role},set:d=>{sessionStorage.token=d.token;sessionStorage.role=d.role;sessionStorage.name=d.name||''},clear:()=>{sessionStorage.clear();localStorage.clear()}};
async function api(path,o={}){let h={'Content-Type':'application/json',...(o.headers||{})};if(sess.token)h.Authorization='Bearer '+sess.token;let r=await fetch('/api'+path,{...o,headers:h}),d=await r.json();if(!r.ok){if(r.status===401)sess.clear();throw Error(d.error||'Request failed')}return d}
function selectRole(role){$('#loginRole').value=role;document.querySelectorAll('[data-login-role]').forEach(b=>b.classList.toggle('active',b.dataset.loginRole===role));let i=$('#loginIdentity');i.name=role==='student'?'studentId':'username';i.placeholder=role==='student'?'Student ID':'Username';$('#loginSubtitle').textContent=role==='student'?'Sign in to view your room and complaints.':'Sign in to manage your hostel.';$('#loginMessage').textContent=''}
document.querySelectorAll('[data-login-role]').forEach(b=>b.onclick=()=>selectRole(b.dataset.loginRole));
$('#loginForm').onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),student=d.role==='student';try{let r=await api(student?'/student/login':'/login',{method:'POST',body:JSON.stringify(student?{studentId:d.studentId,password:d.password}:{username:d.username,password:d.password})});sess.set(r);showApp()}catch(x){$('#loginMessage').textContent=x.message}};
function showApp(){if(!sess.token)return;let student=sess.role==='student';$('#login').hidden=true;$('#app').hidden=false;$('#adminNav').hidden=student;$('#studentNav').hidden=!student;$('#appLabel').textContent=student?'STUDENT PORTAL':'HOSTEL ADMINISTRATION';$('#avatar').textContent=(sessionStorage.name||(student?'S':'A'))[0].toUpperCase();document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));go(student?'student-dashboard':'dashboard')}
async function logout(){try{await api('/logout',{method:'POST'})}catch(_){}sess.clear();history.replaceState(null,'',location.pathname);location.replace('/')}$('#logout').onclick=logout;
window.addEventListener('pageshow',e=>{if(e.persisted&&!sess.token)location.replace('/')});
function go(n){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===n));let t={dashboard:'Dashboard',students:'Students','add-student':'Add Student',rooms:'Rooms',complaints:'Complaints',ai:'AI Hostel Assistant','student-dashboard':'Dashboard','submit-complaint':'Submit Complaint','complaint-status':'Complaint Status',rules:'Hostel Rules / Facilities'};$('#title').textContent=t[n];({dashboard,students,'add-student':openAddStudent,rooms,complaints,ai,'student-dashboard':studentDashboard,'submit-complaint':submitComplaint,'complaint-status':complaintStatus,rules})[n]().catch(x=>page.innerHTML=`<div class="panel"><h3>Could not load this page</h3><p class="hint">${esc(x.message)}</p></div>`)}
async function dashboard(){let d=await api('/dashboard');page.innerHTML=`<div class="cards">${[['Total Students',d.totalStudents],['Total Rooms',d.totalRooms],['Available Rooms',d.availableRooms],['Occupied Rooms',d.occupiedRooms],['Pending Complaints',d.pendingComplaints],['Resolved Complaints',d.resolvedComplaints]].map(x=>`<div class="card"><p>${x[0]}</p><strong>${x[1]}</strong></div>`).join('')}</div><div class="panel"><h3>Welcome to Smart Hostel</h3><p class="hint">Use the navigation to manage residents, rooms, complaints, and AI-supported help.</p></div>`}
async function studentDashboard(){let[s,c]=await Promise.all([api('/student/me'),api('/student/complaints')]);page.innerHTML=`<div class="panel"><p class="eyebrow">YOUR HOSTEL SPACE</p><h2>Welcome, ${esc(s.name)}</h2><p class="hint">Your information and requests are private to your account.</p></div><div class="cards"><div class="card"><p>Student ID</p><strong>${s.id}</strong></div><div class="card"><p>Room</p><strong>${esc(s.hostelBlock)}-${s.roomNumber}</strong></div><div class="card"><p>Open complaints</p><strong>${c.filter(x=>x.status!=='Resolved').length}</strong></div></div><div class="panel"><h3>Your details</h3><p><b>Branch:</b> ${esc(s.branch)} &nbsp; <b>Year:</b> ${s.year}</p><p><b>Hostel:</b> ${esc(s.hostelBlock)} &nbsp; <b>Room:</b> ${s.roomNumber}</p></div>`}
function table(rows,admin=false){return !rows.length?'<p class="hint">No complaints have been submitted yet.</p>':`<table><thead><tr><th>ID</th>${admin?'<th>Student</th>':''}<th>Category</th><th>Description</th><th>Date</th><th>Status</th>${admin?'<th>Update</th>':''}</tr></thead><tbody>${rows.map(c=>`<tr><td>${c.complaintId}</td>${admin?`<td>${c.studentId}</td>`:''}<td>${esc(c.category)}</td><td>${esc(c.description)}</td><td>${esc(c.date)}</td><td><span class="tag ${c.status==='Resolved'?'resolved':''}">${esc(c.status)}</span></td>${admin?`<td><select onchange="updateComplaint(${c.complaintId},this.value)"><option>${esc(c.status)}</option><option>Pending</option><option>In Progress</option><option>Resolved</option></select></td>`:''}</tr>`).join('')}</tbody></table>`}
async function submitComplaint(){page.innerHTML='<div class="panel"><h3>Submit Complaint</h3><form id="studentComplaintForm"><input name="category" placeholder="Category (e.g. Maintenance)" required><textarea name="description" placeholder="Describe the issue" required></textarea><button>Submit complaint</button></form></div>';$('#studentComplaintForm').onsubmit=async e=>{e.preventDefault();await api('/student/complaints',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});go('complaint-status')}}
async function complaintStatus(){page.innerHTML=`<div class="panel"><h3>Complaint Status</h3>${table(await api('/student/complaints'))}</div>`}
function rules(){page.innerHTML='<div class="panel"><h3>Hostel Rules</h3><ol><li>Keep your room and common spaces clean.</li><li>Report maintenance and safety issues promptly.</li><li>Respect quiet hours and other residents.</li><li>Follow hostel entry, visitor, and security procedures.</li><li>Contact hostel administration for urgent concerns.</li></ol></div>'}
function addStudentForm(){return '<div class="panel" id="editor"><div class="toolbar"><h3>Add Student</h3><button class="danger" id="close">Close</button></div><form id="addStudentForm" class="grid"><input name="id" type="number" placeholder="Student ID" required><input name="name" placeholder="Student name" required><input name="password" type="password" placeholder="Password" required><input name="phone" placeholder="Phone" required><input name="address" placeholder="Address" required><input name="gender" placeholder="Gender" required><input name="branch" placeholder="Branch" required><input name="year" type="number" placeholder="Year" required><input name="parentPhone" placeholder="Parent phone" required><input name="hostelBlock" placeholder="Hostel block" required><input name="roomNumber" type="number" placeholder="Room number" required><button class="full">Create student account</button></form></div>'}
async function students(){let r=await api('/students');page.innerHTML=`<div class="panel"><table><thead><tr><th>ID</th><th>Name</th><th>Branch</th><th>Room</th><th>Phone</th></tr></thead><tbody>${r.map(s=>`<tr><td>${s.id}</td><td>${esc(s.name)}</td><td>${esc(s.branch)}</td><td>${esc(s.hostelBlock)}-${s.roomNumber}</td><td>${esc(s.phone)}</td></tr>`).join('')}</tbody></table></div>`}
function openAddStudent(){page.innerHTML=addStudentForm();$('#close').onclick=()=>go('students');$('#addStudentForm').onsubmit=async e=>{e.preventDefault();try{await api('/students',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});go('students')}catch(x){alert(x.message)}}}
async function rooms(){let r=await api('/rooms');page.innerHTML=`<div class="panel"><table><thead><tr><th>Room</th><th>Block</th><th>Capacity</th><th>Occupied beds</th><th>Status</th></tr></thead><tbody>${r.map(x=>`<tr><td>${x.roomNumber}</td><td>${esc(x.block)}</td><td>${x.capacity}</td><td>${x.occupiedBeds}</td><td>${esc(x.status)}</td></tr>`).join('')}</tbody></table></div>`}
async function complaints(){page.innerHTML=`<div class="panel">${table(await api('/complaints'),true)}</div>`}window.updateComplaint=async(i,s)=>{await api('/complaints/'+i,{method:'PUT',body:JSON.stringify({status:s})});complaints()};
async function ai(){page.innerHTML='<div class="panel"><h3>AI Hostel Assistant</h3><p class="hint">Ask about rules, rooms, complaints, or hostel processes.</p><div class="chat" id="chat"><div class="bubble">Hello! How can I help?</div></div><form id="chatForm" class="toolbar"><input id="question" placeholder="Type your question..." required><button>Send</button></form></div>';$('#chatForm').onsubmit=async e=>{e.preventDefault();let q=$('#question').value;$('#chat').innerHTML+=`<div class="bubble me">${esc(q)}</div>`;let r=await api('/ai/chat',{method:'POST',body:JSON.stringify({message:q})});$('#chat').innerHTML+=`<div class="bubble">${esc(r.reply)}</div>`;$('#question').value=''}}
if(sess.token&&sess.role)showApp();else selectRole('admin');
